# Release notes.
# This is a valid YAML file.
# It should contain some metadata about the feature/bug etc that you are working on.
# The CI process tries to validate that you have added the required metadata to this file.
# ie; CI will fail if it detects no changes in this file.

# The items that are neccessary are:
  # 1. pull_request. This is a link to the github pull request that contains your changes.
  # 2. jira_card. This is a link to the jira card that you were working on.
  # 3. release_type. This is the type of change that your changes entails. There are 4 types of releases:
    # a. code
    # b. infra
    # c. config
    # d. migration
    # Your changes should be labelled with one of the above.
  # 4. tagging_strategy. This is either MAJOR, MINOR or PATCH. see https://semver.org/ for their meaning
  # 5. release_title. The title you would prefer to be added to the release.
  # 6. release_notes. This is a YAML list of the changes that your PR contains.

# An example is shown below:

# pull_request: https://github.com/komuw/hey/pull/2
# jira_card: https://komuprod.atlassian.net/browse/JKL-207
# release_type: config
# tagging_strategy: patch
# release_title: support multiple Auth Keys in Login API.
# release_notes:
# - added a feature to enable users to login
# - fixed a bug where admin users were been automatically logged out every 5 minutes
# - added integration to twitter API.


pull_request: https://github.com/komuw/hey/pull/19
jira_card: https://komuprod.atlassian.net/browse/SH-565
release_type: infra
tagging_strategy: PATCH
release_title: Migrate to GCP cloud
release_notes:
- replaced AWS S3 with Google cloud buckets.
- replaced AWS kubernetes with google cloud kubernetes service.
- replaced AWS ELB with Google cloud Geo load balancers.
