version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip3 install -e .[dev,test,alldns]

      - run:
          name: run tests
          command: |
            echo "no tests now"

      - run:
          name: deploy
          command: |      
            python releaser.py