version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip3 install -e .[dev,test,alldns]

      - run:
          name: run tests
          command: |
            flake8 releaser.py
            pylint --enable=E --disable=W,R,C --unsafe-load-any-extension=y releaser.py

      - run:
          name: deploy
          command: |
            chmod -R a+rwx ~/repo
            stat ~/repo
            python releaser.py